schema:
  - ./src/schema/schema.json
documents: ./src/**/*.graphql
extensions:
  nitrogql:
    generate:
      type:
        scalarTypes:
          DateTime: Date
          UUID: string
      mode: with-loader-ts-5.0
      schemaOutput: ./src/generated/schema.d.ts
      name:
        fragmentTypeSuffix: "Fragment"
        fragmentVariableSuffix: "Fragment"
